### ISSUE TITLE
Can you type utf8 font? I want to translate it into Thai too.

### ISSUE THREAD

**Issue by watchakorn-18k** [TeamPBCN/Metroid-Samus-Returns#4]

**Comment by watchakorn-18k** [comment]
> Please try to follow [this](https://github.com/TeamPBCN/Metroid-Samus-Returns/issues/1#issuecomment-903509470) guide to use the tools in this repo.

Do you have the full rom file? I extracted the file and looked for romfs, it didn't find romfs. 😂

**Comment by JokerDKha** [comment]
@watchakorn-18k im will help you out, contact me in discord  JokerD#0461

**Comment by LITTOMA** [comment]
How's it going? If you have any problems feel free to ask here

**Comment by watchakorn-18k** [comment]
> How's it going? If you have any problems feel free to ask here

Can you describe it in a video or new? I'm new to this @LITTOMA

**Comment by Hambaka** [comment]
@watchakorn-18k
Do you still need help? I try replace the text on title screen to Thai language and at least it works.
![msr_thai_test](https://user-images.githubusercontent.com/20476755/140607498-1d7bf15f-ff69-4dc2-b0c4-41faac070314.png)
It is just for test, and I don't understand Thai, so the translation is from Google translate. Font is "Noto Sans Thai", the "NotoSansThai-SemiBold.ttf" one. 
(The subtitle of the title image is in Simplified Chinese, because I test Thai based on my project)

**Comment by watchakorn-18k** [comment]
> @watchakorn-18k It is just for test, and I don't understand Thai, so the translation is from Google translate. Font is "Noto Sans Thai", the "NotoSansThai-SemiBold.ttf" one.
(The subtitle of the title image is in Simplified Chinese, because I test Thai based on my project) ![msr_thai_test](https://user-images.githubusercontent.com/20476755/140607498-1d7bf15f-ff69-4dc2-b0c4-41faac070314.png)

Wow, how can i contact you do you have Discord?

**Comment by Hambaka** [comment]
@watchakorn-18k 
Sure, my Discord ID is `Hambaka [UTC+8]#4798`

Edit: The font issue is solved for now.

@LITTOMA 我跟他聊了大概两个小时，他的Python 2.7环境和模拟器测试环境貌似有点问题，虽然能够正常导出文本并编译回二进制文件，但是字库生成有问题。由于泰文字母不多，我就从维基百科上复制了一下完整泰文字母列表，根据他发过来的ttf字体文件生成了一份字库，但是他的模拟器环境又有问题，读不出来字库。反正最后试了一会好说歹说可以正常显示泰文了，所以目前这个issue也算是某种意义上解决了。
